version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./ecommerce_api
      dockerfile: Dockerfile
    volumes:
      - ./ecommerce_api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DB_NAME=ecommerce_db
      - DB_USER=postgresadmin
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build:
      context: ./e-commerce
    volumes:
      - ./e-commerce:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm i && npm run dev"
    depends_on:
      - backend

volumes:
  postgres_data:
